receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 25

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

exporters:
  otlphttp/upstream:
    endpoint: ${env:UPSTREAM_OTLP_HTTP_ENDPOINT}
    headers:
      Authorization: ${env:UPSTREAM_OTLP_AUTHORIZATION}
  debug:
    verbosity: normal

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/upstream]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/upstream]
